"""Initial migration

Revision ID: 779859a453a9
Revises: 
Create Date: 2025-07-23 20:23:11.066853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '779859a453a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slot')
    op.drop_table('slot_booking')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slot_booking',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('booking_id', sa.INTEGER(), nullable=False),
    sa.Column('slot_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['slot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slot',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('parking_lot_id', sa.INTEGER(), nullable=False),
    sa.Column('size', sa.VARCHAR(length=10), nullable=True),
    sa.Column('is_available', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['parking_lot_id'], ['parking_lot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
